const biggestCities = [
    'Scottsdale, AZ',
    'Orlando, FL',
    'Cincinnati, OH',
    'Las Vegas, NV',
    'San Francisco, CA',
    'Winston-Salem, NC',
    'Los Angeles, CA',
    'Savannah, GA',
    'Augusta, GA',
    'Rochester, NY',
    'San Antonio, TX',
    'Toledo, OH',
    'Atlanta, GA',
    'Birmingham, AL',
    'Tucson, AZ',
    'Pasadena, CA',
    'Houston, TX',
    'Tulsa, OK',
    'Durham, NC',
    'Corona, CA',
    'Phoenix, AZ',
    'Henderson, NV',
    'Charleston, SC',
    'Dallas, TX',
    'Escondido, CA',
    'Lexington, KY',
    'Chandler, AZ',
    'Port St. Lucie, FL',
    'Hollywood, FL',
    'Charlotte, NC',
    'Surprise, AZ',
    'Austin, TX',
    'Frisco, TX',
    'Louisville, KY',
    'Peoria, AZ',
    'Irvine, CA',
    'Alexandria, VA',
    'Carrollton, TX',
    'Knoxville, TN',
    'Virginia Beach, VA',
    'Fullerton, CA',
    'Ontario, CA',
    'Grand Rapids, MI',
    'Roseville, CA',
    'Spokane, WA',
    'Lubbock, TX',
    'Akron, OH',
    'Tampa, FL',
    'Fort Wayne, IN',
    'Salt Lake City, UT',
    'Thornton, CO',
    'Pomona, CA',
    'Chula Vista, CA',
    'Springfield, MO',
    'Kansas City, MO',
    'Lincoln, NE',
    'McKinney, TX',
    'Overland Park, KS',
    'Rockford, IL',
    'Oceanside, CA',
    'Riverside, CA',
    'Reno, NV',
    'San Diego, CA',
    'New York, NY',
    'Indianapolis, IN',
    'Hayward, CA',
    'Olathe, KS',
    'St. Louis, MO',
    'Anaheim, CA',
    'Mesa, AZ',
    'Greensboro, NC',
    'Irving, TX',
    'Santa Rosa, CA',
    'Yonkers, NY',
    'Santa Ana, CA',
    'Fontana, CA',
    'Fort Worth, TX',
    'Miami, FL',
    'Pembroke Pines, FL',
    'Huntington Beach, CA',
    'Murfreesboro, TN',
    'Sioux Falls, SD',
    'Boise City, ID',
    'Arlington, TX',
    'Aurora, CO',
    'Kansas City, KS',
    'Montgomery, AL',
    'Richmond, VA',
    'Long Beach, CA',
    'Tacoma, WA',
    'Jacksonville, FL',
    'Plano, TX',
    'Albuquerque, NM',
    'Aurora, IL',
    'Oxnard, CA',
    'Boston, MA',
    'Oklahoma City, OK',
    'Chesapeake, VA',
    'Columbus, OH',
    'Grand Prairie, TX',
    'Springfield, MA',
    'Colorado Springs, CO',
    'Glendale, AZ',
    'Mobile, AL',
    'Mesquite, TX',
    'Raleigh, NC',
    'Killeen, TX',
    'Madison, WI',
    'Amarillo, TX',
    'Jackson, MS',
    'Macon, GA',
    'Waco, TX',
    'Tempe, AZ',
    'Naperville, IL',
    'Dayton, OH',
    'San Bernardino, CA',
    'Newark, NJ',
    'Stockton, CA',
    'Chattanooga, TN',
    'Tallahassee, FL',
    'Eugene, OR',
    'Palmdale, CA',
    'Pittsburgh, PA',
    'Omaha, NE',
    'Bakersfield, CA',
    'Des Moines, IA',
    'New Orleans, LA',
    'Moreno Valley, CA',
    'St. Paul, MN',
    'Fort Collins, CO',
    'Midland, TX',
    'North Las Vegas, NV',
    'Jersey City, NJ',
    'Shreveport, LA',
    'Salinas, CA',
    'Norfolk, VA',
    'Joliet, IL',
    'Newport News, VA',
    'Glendale, CA',
    'Fayetteville, NC',
    'Hialeah, FL',
    'Wichita, KS',
    'Little Rock, AR',
    'Memphis, TN',
    'St. Petersburg, FL',
    'Garland, TX',
    'Minneapolis, MN',
    'Philadelphia, PA',
    'Portland, OR',
    'Syracuse, NY',
    'Corpus Christi, TX',
    'Rancho Cucamonga, CA',
    'Clarksville, TN',
    'El Paso, TX',
    'McAllen, TX',
    'Cape Coral, FL',
    'Sacramento, CA',
    'Bellevue, WA',
    'Baton Rouge, LA',
    'Chicago, IL',
    'Salem, OR',
    'Denver, CO',
    'San Jose, CA',
    'Oakland, CA',
    'Detroit, MI',
    'Brownsville, TX',
    'Fresno, CA',
    'Nashville, TN',
    'Worcester, MA',
    'Providence, RI',
    'Sunnyvale, CA',
    'Washington, DC',
    'Lakewood, CO',
    'Seattle, WA',
    'Laredo, TX',
    'Torrance, CA',
    'Vancouver, WA',
    'Elk Grove, CA',
    'Baltimore, MD',
    'Columbus, GA',
    'Huntsville, AL',
    'Fort Lauderdale, FL',
    'Milwaukee, WI',
    'Hampton, VA',
    'Modesto, CA',
    'Denton, TX',
    'Buffalo, NY',
    'Anchorage, AK',
    'Cleveland, OH',
    'Lancaster, CA',
    'West Valley City, UT',
    'Fremont, CA',
    'Garden Grove, CA',
    'Orange, CA',
    'Paterson, NJ',
    'Santa Clarita, CA',
    'Miramar, FL',
    'Warren, MI',
    'Bridgeport, CT',
    'Pasadena, TX',
]

export default biggestCities
